const SUBJECTS={math:{id:"math",name:"الرياضيات",description:"جبر وهندسة",icon_url:"https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=800&q=80",teacher:"أ. خالد المنذري"},islamic:{id:"islamic",name:"التربية الإسلامية",description:"فقه وتفسير",icon_url:"https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=800&q=80",teacher:"أ. فاطمة الهنائي"},arabic:{id:"arabic",name:"اللغة العربية",description:"نحو وبلاغة",icon_url:"https://images.unsplash.com/photo-1456513080800-7d93d16e6986?auto=format&fit=crop&w=800&q=80",teacher:"أ. سعيد الرواحي"},science:{id:"science",name:"العلوم",description:"تجارب",icon_url:"https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80",teacher:"أ. مريم البلوشي"}};
const DEFAULT_DB={students:{"uid_student_demo":{name:"يوسف العلوي",email:"student@hassad.om",grade:"الصف الثامن",subscription_status:"active",subscription_expiry:"2026-12-31"},"uid_layan":{name:"ليان الشامسي",email:"layan@hassad.om",grade:"الصف التاسع",subscription_status:"active"},"uid_hamad":{name:"حمد الكندي",email:"hamad@hassad.om",grade:"الصف الثامن",subscription_status:"inactive"}},subjects:SUBJECTS,assignments:[{id:"a1",title:"واجب الأعداد الصحيحة",subject_id:"math",description:"شجرة العوامل",due_date:"2026-09-20",created_at:"2026-09-14"},{id:"a2",title:"تعبير كتابي: وطني عمان",subject_id:"arabic",description:"150 كلمة",due_date:"2026-09-22",created_at:"2026-09-15"},{id:"a3",title:"تقرير التمثيل الضوئي",subject_id:"science",description:"صور التجربة",due_date:"2026-09-18",created_at:"2026-09-12"},{id:"a4",title:"حفظ سورة الملك",subject_id:"islamic",description:"معاني",due_date:"2026-09-25",created_at:"2026-09-16"}],submissions:{},live_sessions:[{id:"l1",title:"حصة المعادلات الخطية",subject_id:"math",stream_url:"",scheduled_time:"2026-09-17T20:00:00",status:"upcoming"},{id:"l2",title:"فقه العبادات",subject_id:"islamic",stream_url:"",scheduled_time:"2026-09-18T17:00:00",status:"upcoming"},{id:"l3",title:"البلاغة",subject_id:"arabic",stream_url:"",scheduled_time:"2026-09-19T19:00:00",status:"upcoming"},{id:"l4",title:"الخلايا",subject_id:"science",stream_url:"",scheduled_time:"2026-09-20T18:00:00",status:"upcoming"}],lessons:[{subject_id:"math",title:"العمليات على الكسور",duration:"32 د"},{subject_id:"math",title:"المثلثات المتشابهة",duration:"28 د"},{subject_id:"islamic",title:"أركان الإيمان",duration:"24 د"},{subject_id:"arabic",title:"علامات الإعراب",duration:"36 د"},{subject_id:"science",title:"حالات المادة",duration:"30 د"}]};
function db(){const raw=localStorage.getItem("hassad-db");if(!raw){localStorage.setItem("hassad-db",JSON.stringify(DEFAULT_DB));return structuredClone(DEFAULT_DB)}return JSON.parse(raw)}
function saveDb(next){localStorage.setItem("hassad-db",JSON.stringify(next))}
function currentUser(){const raw=localStorage.getItem("hassad-user");return raw?JSON.parse(raw):null}
function requireAuth(role){const user=currentUser();if(!user){location.href="login.html";return null}if(role&&user.role!==role){location.href=user.role==="teacher"?"admin.html":"dashboard.html";return null}return user}
function logout(){localStorage.removeItem("hassad-user");location.href="index.html"}
function toast(msg){let el=document.querySelector(".toast");if(!el){el=document.createElement("div");el.className="toast";document.body.appendChild(el)}el.textContent=msg;el.style.display="block";setTimeout(()=>el.style.display="none",2200)}
function studentByUid(uid){return db().students[uid]||null}
function canAccessContent(student){return !!student&&student.subscription_status==="active"}
function assignmentsBySubject(subjectId){return db().assignments.filter(a=>a.subject_id===subjectId).sort((a,b)=>(b.created_at||"").localeCompare(a.created_at||""))}
function latestLive(subjectId){const sessions=db().live_sessions.filter(s=>s.subject_id===subjectId&&s.status!=="completed").sort((a,b)=>(a.scheduled_time||"").localeCompare(b.scheduled_time||""));return sessions[0]||{title:"لا حصة مجدولة",scheduled_time:"",stream_url:"",status:"upcoming"}}
function loginHandler(e){e.preventDefault();const email=document.getElementById("email").value.trim().toLowerCase();const password=document.getElementById("password").value;const err=document.getElementById("login-error");if(email==="teacher@hassad.om"&&password==="123456"){localStorage.setItem("hassad-user",JSON.stringify({email,name:"إدارة حَصاد",role:"teacher",uid:"uid_teacher"}));location.href="admin.html";return}const data=db();const entry=Object.entries(data.students).find(([,s])=>s.email===email);if(!entry||password!=="123456"){err.textContent="بيانات الدخول غير صحيحة.";return}const[uid,student]=entry;localStorage.setItem("hassad-user",JSON.stringify({email:student.email,name:student.name,role:"student",uid,grade:student.grade,subscription_status:student.subscription_status}));location.href="dashboard.html"}
function renderDashboard(){const user=requireAuth("student");if(!user)return;document.getElementById("welcome").textContent=`مرحباً ${user.name}`;const data=db();const wrap=document.getElementById("subject-grid");if(!canAccessContent(studentByUid(user.uid)||user)){wrap.innerHTML=`<div class="card" style="grid-column:1/-1"><h3>الاشتراك غير نشط</h3></div>`;return}wrap.innerHTML=Object.values(data.subjects).map(s=>{const live=latestLive(s.id);return `<a class="card mini-subject" href="subject.html?id=${s.id}"><img src="${s.icon_url}" alt="${s.name}"><h3>${s.name}</h3><p style="color:var(--muted);font-size:13px">${s.teacher||""}</p><div class="badge badge-soon" style="margin-top:10px">${live.scheduled_time||live.title}</div></a>`}).join("");document.getElementById("assignment-list").innerHTML=data.assignments.map(a=>{const sub=data.submissions[`${a.id}_${user.uid}`];return `<div class="row"><div><strong>${a.title}</strong><div style="color:var(--muted);font-size:13px">${data.subjects[a.subject_id].name} — ${a.due_date}</div></div><span class="badge ${sub?"badge-done":"badge-wait"}">${sub?"مُسلَّم":"مفتوح"}</span></div>`}).join("")}
function renderSubject(){const user=requireAuth("student");if(!user)return;const id=new URLSearchParams(location.search).get("id")||"math";const data=db();const s=data.subjects[id];const live=latestLive(id);document.getElementById("subject-title").textContent=s.name;document.getElementById("subject-teacher").textContent=s.teacher||s.description;document.getElementById("live-meta").textContent=`${live.title} — ${live.scheduled_time||""}`;const player=document.getElementById("player");player.innerHTML=live.stream_url?`<iframe src="${live.stream_url}" allowfullscreen></iframe>`:`<div class="player-empty"><div><h3>سيظهر البث هنا</h3><p>عندما يضيف المعلم رابط التضمين</p></div></div>`;document.getElementById("lessons").innerHTML=data.lessons.filter(l=>l.subject_id===id).map(l=>`<div class="row"><div><strong>${l.title}</strong></div><span class="badge badge-wait">${l.duration}</span></div>`).join("");document.getElementById("hw").innerHTML=assignmentsBySubject(id).map(a=>{const sub=data.submissions[`${a.id}_${user.uid}`];return `<div class="row"><div><strong>${a.title}</strong><div style="color:var(--muted);font-size:13px">${a.description}<br>آخر موعد: ${a.due_date}</div></div><button class="btn" onclick="Hassad.submitWork('${a.id}')">${sub?"إعادة التسليم":"تسليم"}</button></div>`}).join("")}
function submitWork(assignmentId){const user=currentUser();if(!user)return;const data=db();data.submissions[`${assignmentId}_${user.uid}`]={assignment_id:assignmentId,student_uid:user.uid,status:"submitted",submitted_at:new Date().toISOString()};saveDb(data);toast("تم التسليم");renderSubject()}
function switchTab(name,btn){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.getElementById("panel-"+name).classList.add("active");btn.classList.add("active")}
function renderAdmin(){const user=requireAuth("teacher");if(!user)return;const data=db();document.getElementById("live-form-subject").innerHTML=Object.values(data.subjects).map(s=>`<option value="${s.id}">${s.name}</option>`).join("");document.getElementById("hw-subject").innerHTML=Object.values(data.subjects).map(s=>`<option value="${s.id}">${s.name}</option>`).join("");document.getElementById("live-table").innerHTML=data.live_sessions.map(l=>`<tr><td>${data.subjects[l.subject_id]?.name||l.subject_id}</td><td>${l.title}</td><td>${l.scheduled_time}</td><td>${l.stream_url?"مربوط":"بدون رابط"}</td></tr>`).join("");document.getElementById("admin-hw").innerHTML=data.assignments.map(a=>`<div class="row"><div><strong>${a.title}</strong><div style="color:var(--muted);font-size:13px">${data.subjects[a.subject_id].name} — ${a.due_date}</div></div></div>`).join("");document.getElementById("students").innerHTML=Object.values(data.students).map(st=>`<tr><td>${st.name}</td><td>${st.email}</td><td>${st.grade}</td><td><span class="badge ${st.subscription_status==="active"?"badge-done":"badge-live"}">${st.subscription_status==="active"?"نشط":"موقوف"}</span></td></tr>`).join("")}
function saveLive(e){e.preventDefault();const data=db();data.live_sessions.unshift({id:"l"+Date.now(),title:document.getElementById("live-title").value,subject_id:document.getElementById("live-form-subject").value,stream_url:document.getElementById("live-embed").value.trim(),scheduled_time:document.getElementById("live-time").value,status:document.getElementById("live-embed").value.trim()?"live":"upcoming"});saveDb(data);toast("تم نشر الحصة");renderAdmin();e.target.reset()}
function saveHw(e){e.preventDefault();const data=db();data.assignments.unshift({id:"a"+Date.now(),subject_id:document.getElementById("hw-subject").value,title:document.getElementById("hw-title").value,description:"واجب جديد",due_date:document.getElementById("hw-due").value,created_at:new Date().toISOString().slice(0,10)});saveDb(data);toast("تم نشر الواجب");renderAdmin();e.target.reset()}
window.Hassad={loginHandler,logout,renderDashboard,renderSubject,renderAdmin,switchTab,saveLive,saveHw,submitWork,toast,currentUser};
